num=[12,22,33,44,55,66,77,88,99]
n=len(num)
print("Length",n)
num.append(100)
print("Append used",num)
num.insert(4,45)
print("Insert used",num)
num1=num.copy()
print("Copy used",num1)
num.extend(num1)
print("Extend used",num)
num1.pop()
print("num1 after poping last element",num1)
num1.remove(99)
print("num1 after removing 99",num1)
num1.sort()
print("num1 after sorting",num1)
num1.reverse()
print("num1 after reversing ",num1)
num1.clear()
print("num1 after clearing",num1)
large=max(num)
print("Maximum of num=",large)
small=min(num)
print("Minimum of num=",small)

